export const Icons = {
  mobile_alt: require('../assets/icons/mobile_alt.png'),
  password: require('../assets/icons/password.png'),
  eye_close: require('../assets/icons/eye_close.png'),
  tag_outline: require('../assets/icons/tag_outline.png'),
  user_square: require('../assets/icons/user_square.png'),
  mail: require('../assets/icons/mail.png'),
  home: require('../assets/icons/home.png'),
  bag: require('../assets/icons/bag.png'),
  bag_new: require('../assets/icons/bag_new.png'),

  //bag_new
  calendar: require('../assets/icons/calendar.png'),
  time_circle: require('../assets/icons/time_circle.png'),
  profile: require('../assets/icons/profile.png'),
  exit: require('../assets/icons/exit.png'),
  exitR: require('../assets/icons/exit_r.png'),
  exit_o: require('../assets/icons/exit_o.png'),
  notification: require('../assets/icons/notification.png'),
  notificationR: require('../assets/icons/notification_r.png'),
  notification_o: require('../assets/icons/notification_o.png'),
  search: require('../assets/icons/search.png'),
  cart: require('../assets/icons/cart.png'),
  back_arrow: require('../assets/icons/back_arrow.png'),
  menu: require('../assets/icons/menu.png'),
  settings: require('../assets/icons/settings.png'),
  grid: require('../assets/icons/grid.png'),
  share: require('../assets/icons/share.png'),
  drop_icon: require('../assets/icons/drop_icon.png'),
  right_arrow: require('../assets/icons/right_arrow.png'),
  checked: require('../assets/icons/checked.png'),
  uncheck: require('../assets/icons/uncheck.png'),
  pencil: require('../assets/icons/pencil.png'),
  delete: require('../assets/icons/delete.png'),
  bell_fill: require('../assets/icons/bell_fill.png'),
  booking_plus_icon: require('../assets/icons/plus_logo_150_150.png'),
};
