/* eslint-disable no-undef */
const devMode = __DEV__;
export const baseUrl = 'http://103.253.14.203:4029/Mainapi/';
const BaseSetting = {
  name: 'Mydemo',
  displayName: 'Mydemo',
  appVersionCode: '1',
  baseUrl,
  api: `${baseUrl}/api`,
  shareEndPoint: baseUrl,
  socketUrl: baseUrl,
  endpoints: {
    deleteUser: '/deleteUser',
    forgotPasscodeReset: '/forgotPasscodeReset',
    signUpOtp: '/signUpOtp',
    customerLogin: '/customerLogin',
    signUpOtpVerify: '/signUpOtpVerify',
    signUpCustomer: '/signUpCustomer',
    // bookAppointment: '/bookAppointmentTnc',
    bookAppointment: '/bookAppointmentTncNew',
    checkAppointmentSlot: '/CheckAppointmentSlotNew',
    appointmentSearch: '/appointmentSearchF21',
    appTransSearchInvoice: '/appTransSearchInvoiceDetail', //appTransSearchInvoice
    changePasscode: '/changePasscode',
    availableSlots: '/AvailableSlots',
    getStaffMemberList: '/getStaffMemberList',
    cartItemInput: '/CartItemInput',
    cartItemDelete: '/CartItemDelete',
    customerReferalCode: '/customerReferalCode',
    sendOtp: '/sendOtp',
    updateCustomerProfile: '/updateCustomerProfile',
    getSaloonList: '/getSaloonList?siteCode=&userID=',
    appointmentCancel: '/appointmentCancel',
    feedbackF21: '/feedbackF21',
    profilePicture: '/updateProfileF21',
    profilePic: '/profilePicture',
    createAddress: '/createAddress',
    updateAddress: '/updateAddress',
    stripeCustomerCreate: '/StripeCustomerCreate',
    stripePaymentIntentCreate: '/StripePaymentIntentCreate',
    stripePaymentIntentConfirm: '/StripePaymentIntentConfirm',
    appTransPostSales: '/appTransPostSalesTnc',
    mypackages: '/mypackages',
    myProducts: '/myProducts',
    cartAllItemDelete: '/cartAllItemDelete',
    homeBanner: '/dashBoardF21',
    setFcmToken: '/fcmTokenForCustomerApp',
    availableSlotsTnc: '/AvailableSlotsTnc',
    AvailableStaffsTnc: '/AvailableStaffsTnc',
    updateNotificationStatus: '/updatePushNotificationStatus',
    getClientDetails: '/getClientDetails',
  },
};

export default BaseSetting;
